kata = '    oJam aNAK bABi   '
print(kata.lower())
print(kata.upper())
print(kata.rstrip())
print(kata.lstrip())
print(kata.strip())
print(kata.strip('aNAK'))
print(kata.endswith('i'))
print(kata.endswith(' '))
print(kata.join(['Dicoding','Indonesia', '!']))
print(kata.split())
print(kata.replace(' ', ''))
print(kata.isalpha)
print(kata.i)